### ISSUE TITLE
Search doesn't work when using non-ascii chars

### ISSUE THREAD

**Issue by VeryBigSad** [vigilant-umbrella/wikiHowUnofficialAPI#13]
Hello!
This sample code will throw out this error:
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-28: ordinal not in range(128)`
```py
import wikihowunofficialapi as wha

search_text = "тест"  # "test" in russian
max_results = 1
data = wha.search_wikihow(search_text, max_results, lang='ru')[0]
```
Problem occurs when python http libriary (which is used by urllib, which is used by you) tries to encode the URL you make in `WikiHow.search()` function. You put the `search_term` variable in the `search_url`, but since it's non-ascii, it cannot be encoded.
What this means is - this library can't work with Cyrillic symbols, though the support for russian version of wikihow is included.

**Comment by aniketsharma00411** [comment]
Thank you so much for pointing this out. I will soon be sending a PR to fix this.

**Comment by aniketsharma00411** [comment]
@VeryBigSad Hey, we have updated the module. Check [version 0.1.1](https://pypi.org/project/wikihowunofficialapi/) at PyPI.
